version: "3"
services:

  vault:
    build:
      dockerfile: Dockerfile.vault
      context: .
    command: server -config=/config.hcl
    environment:
      - MYSQL_HOSTNAME=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE:-vault}
      - MYSQL_USER=${MYSQL_USER:-vault}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-vault}
      - CONFIG_FILE=/config.hcl
      - CONFIG_TEMPLATE=/config.hcl.tmpl
    volumes:
      - ./config/vault.hcl.tmpl:/config.hcl.tmpl:ro
      - ./docker-entrypoint.d:/docker-entrypoint.d:ro
    depends_on:
      - mysql
    ports:
      - "${VAULT_PORT:-8200}:8200"
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    networks:
      - vault_net
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    networks:
      - vault_net
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-vault}
      - MYSQL_USER=${MYSQL_USER:-vault}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-vault}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    restart: unless-stopped
    networks:
      - vault_net
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

networks:
  vault_net:
    driver: bridge
